### ISSUE TITLE
Erreur systématique quand je push sur github

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#103]
To https://github.com/nimdanor/python-pl-bank/
   9a4240e..d9270b5  master -> master
/bin/sh: 2: master: not found
La branche master est paramétrée pour suivre la branche distante master depuis https://nimdanor:•••••••••••••••@github.com/nimdanor/python-pl-bank/.

**Comment by nborie** [comment]
I got the same error (light red area) when I push from pl-test on nborie/cbank

To https://github.com/nborie/Cbank
   36cdce1..7954ac7  master -> master
/bin/sh: 2: master: not found
La branche master est paramétrée pour suivre la branche distante master depuis https://nborie:••••••••••@github.com/nborie/Cbank.

When I git add or when I git commit, both produce light green area.... But it is just color since all these commands work in the end (git add adds, git commit commits and git push really pushes to my repo...).

**Comment by plgitlogin** [comment]
Yes

**Comment by Pavell94000** [comment]
The bug was on gitcmd and it is now fixed.
However the feedback in the console when you push correctly seems broken (@mciissee)

**Comment by nimdanor** [comment]
i just tried on pl-test4 a push and i got the usual error message

To https://github.com/PremierLangage/conceptexo
   9fcfaaf..d9325d4  master -> master
/bin/sh: 2: master: not found
La branche master est paramétrée pour suivre la branche distante master depuis https://plgitlogin:•••••••••••@github.com/PremierLangage/conceptexo.
