### ISSUE TITLE
CONTEXT not updated 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#130]
did the following in an evaluator (qcm_evaluator.pl in python-pl-bank )
dic["text"]=" Berk" 

output(100," bravo" , dic)

the old text  was still visible.

**Comment by ddoyen** [comment]
This is really important to make dynamic feedback.

**Comment by nimdanor** [comment]
This is just a bug no ? 
It should be correct easily no ?
Why 0.6.0 ?

**Comment by qcoumes** [comment]
Yes.
Probably, nobody had the time to took a look at it.
Because 0.5.0 should have been released since 2018-12-01, but we're late.

**Comment by nimdanor** [comment]
I realy woud like to start the second semester with this bug fixed on the production

because more people will write exercises directly on PL and it's an important feature

**Comment by nimdanor** [comment]
Le bug est dans le code suivant (playexo/model/sessionexerciceabstract) 

        else:  # Success
            context = dict(response['context'])
        keys = list(response.keys())
        for key in keys:
            response[key + "__"] = response[key]
            del response[key]
        del response['context__']
        context.update(response) # si je comprend bien les valeurs mises a jours sont avec des __ à la fin 
donc on écrase pas les anciennes.
# l'autre remarque c'est quoi la différence entrre self.context et context
# ne doit on pas faire un udate de self.context plustot que de context ??
# car context n'est plus visible a la sortie de la méthode         
        dic = dict(self.context)
        dic.update(context)
        dic['answers__'] = answers
        return answer, feedback, dic
    # et pourquoi on retourne le dic ici et pas le context

**Comment by nimdanor** [comment]
We drop an eye me and @qcoumes.
We clean up playexo/model/sessionexerciceabstract
but  we can't find in the javascript where the exercise is recharged,
@mciissee can you drop an eye. Because it's between the response to the ajax call and the graphical update.

**Comment by nimdanor** [comment]
any progress on this ??

**Comment by Pavell94000** [comment]
Context is now updated

**Comment by nborie** [comment]
To avoid miscommunications about bugs and behaviors. Perhaps we should turn into smaller cycles of development with less ambitious enhancement (just split them could be enough). 

Also, print the number of the current version of PL-server being run inside the GUI is more and more becoming critical since users are reporting bugs in all direction (without citing the machine, the url, the run version, verbally only, false bug, not reproducible, etc... ).

For this issue #130, on https://pl.u-pem.fr/, this 6 February, defining context['click'] = 0 in my build and applying context['click'] += 1 in my grader, the variable context['click'] stay at 1 after the first run of my grader and stay at 1 event I click submit severals times. I have evidences that my grader is well running since other content are well upated (context['text'] and context['form'] seems to me well updates).This behavior is obtained with the following ressource https://github.com/nborie/OSbank/blob/master/exercises/MCQ/generalities/parametrized_MCQ.pl

**Comment by qcoumes** [comment]
Problem may come from the fact the we don't send the context again to the sandbox once the exercise is build.

**Comment by nimdanor** [comment]
The bug seams to be solved will be closed when in PRODUCTION ;)

**Comment by nborie** [comment]
On preprod, on the version 0.6.0

The context is no more updated (text, form, any_key in context, ...)

**Comment by mciissee** [comment]
If the problem is that the exercice is not refreshed after an evaluation, like for #248, this issue is fixed on fix-239 branch that will be integrated to the next release.

**Comment by nborie** [comment]
There is good chance that all this stuff is related...

I am ready to re-close it once PL resources will be back functionning !

**Comment by nimdanor** [comment]
@qcoumes is this closed ?

**Comment by nborie** [comment]
It is OK for me on prod...

**Comment by nimdanor** [comment]
you mean it's ok on prod
