### ISSUE TITLE
Syntax of the pltp Activity

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/premierlangage#161]
We need to propose differents syntax for PLTP-activities. 

First, it should be possible to use the pltp format to define activity of type PLTP.

In this case the activity should execute some variable of the plpt file at different steps of 
the activity:
```python
 start==
 information+=" Your gonna suffer" 
 difficulty=2
 ==

 next== # applyed to every exercice
 @ time(1mn)
 @ noretry 
 @ set(level=difficulty)
 ==
```
etc.

**Comment by esandier** [comment]
It is a complex problem because you need to describe
1) The scenario of the activity in time: the succession, or branching,  or looping between exercises, which can depend on the outcome of an exercise.

2) How different exercises are displayed, does on replace the other, is it added below, etc...


For 1) you could use python as the langage, and an exercise would be called as in this simple example where two exercises must be repeated (with the same data) until success
```
activity_flow ==
parameters = {'difficulty':1, 'display_title':False}
a_seed = some_seed
sequence = ["pl_1", "pl_2"]
for pl in sequence
     for n in range(10) :
        dic = call_pl(pl, seed = a_seed, destination = 'html_element"+pl, params = parameters)
        if dic['result'] == 'success': break
==
``` 
A variant would not provide a seed in the `call_pl` so the exercise would be repeated with different data until success.

For 2) you would need a tag containing `html` code, which could be this in the above example:
```
activity_display==
<h1> Activity number 45 </h1> 
<div id = "html_element_pl_1"> </div>
<div id = "html_element_pl_2"> </div>
<script>
function pl_1_validate(result){
    if (result != 'success') {
         do something with "html_element_pl_1"
    }
    else{
          do something else with "html_element_pl_1"
    }
};
==
```
Note that upon validation of the exercise, the javascript function `pl_1_validate` is automatically called. 

Of course you would need to provide templates for typical activities, so that the user could use a higher-level interface.
