### ISSUE TITLE
file creation dialog allows "../"-prefixes

### ISSUE THREAD

**Issue by igel-kun** [PremierLangage/premierlangage#189]
it seems that I can create files with unexpected names, I recon this is unintended.
![shot-2019-02-07_14-56-31](https://user-images.githubusercontent.com/1258108/52422417-4e91a500-2af6-11e9-90f0-1fb927c9f51f.jpg)

**Comment by qcoumes** [comment]
Thanks for the report. Indeed '/' is not supposed to be allowed in file creation / rename.

@mciissee Are the file name checked against `settings.FILEBROWSER_DISALLOWED_CHAR` ?

**Comment by mciissee** [comment]
This should be checked on the server side but i added a verification on client side now !

**Comment by qcoumes** [comment]
Yes, I just checked the `filebrowser/views.py`, and both rename and create options contain:

```python
if any(c in target for c in settings.FILEBROWSER_DISALLOWED_CHAR):
    msg = "[MSG]"
    return HttpResponseBadRequest(msg)
```

You use `create_resource()` when creating file and directory ?

**Comment by mciissee** [comment]
Yes I use create_resource and I cannot reproduce this bug everything seems to be work normally.

**Comment by qcoumes** [comment]
I could reproduce it (on pl-preprod at least), try creating a directory name *test*, and inside of it a file/directory named *../test/something*

**Comment by mciissee** [comment]
I'm not allowed to create a resource named ../antoine/bla inside the editor

**Comment by mciissee** [comment]
Ok I see this is a bug with the editor I fixed it now the error create a file named something an ignore the path before. If you refresh the page after you will see the file name correctly.

**Comment by qcoumes** [comment]
Ok, I created this:

![before refresh](https://user-images.githubusercontent.com/24588090/52442249-f58c3600-2b22-11e9-9b5a-45204e0a3dca.png)

And after a refresh:

![after_rexfresh](https://user-images.githubusercontent.com/24588090/52442266-fe7d0780-2b22-11e9-9a9a-a7a78c62b3a4.png)

So there's 2 problem, one server side:

```python
name = os.path.basename(path)
try:
    if any(c in name for c in settings.FILEBROWSER_DISALLOWED_CHAR):
```
We're using `basename` before checking for disallowed char, that's why the '/' wasn't detected.
This could be seems as a feature, as it allow to create a file anywhere in the tree (as long as the parent directory exists), we jsut have to ensure it cannot leave *Yggdrasil*.

Now, the second problem seems to be on the client side, the name should also be updated to the basename of the created file.

**Comment by qcoumes** [comment]
>Ok I see this is a bug with the editor I fixed it now the error create a file named something an ignore the path before. If you refresh the page after you will see the file name correctly.

Perfect !

**Comment by mciissee** [comment]
So should we use basename function or remove it ?

**Comment by qcoumes** [comment]
I think we should keep it, but just update the name properly on the UI.

**Comment by mciissee** [comment]
Now file name are checked client side to disallow the characters in settings.FILEBROWSER_DISALLOWED_CHAR list.
