### ISSUE TITLE
Erratic value substitution between keys in a PL exercise file

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/premierlangage#193]
In a PL exercise file, the keys can be defined using value of other keys. But the substitution order is erratic (because the keys are stored in a dictionary). Is it possible to make the substitutions in the definition order of the keys in the PL file ?

Here are examples of the current behavior.

#### Example 1

PL file:
~~~
key1 = a
key2 = {{ key1 }}

text ==
- key1 : {{ key1 }}
- key2 : {{ key2 }}
==
~~~
Exercise display:
- key1 : a
- key2 : a

#### Example 2

PL file:
~~~
key2 = a
key1 = {{ key2 }}

text ==
- key1 : {{ key1 }}
- key2 : {{ key2 }}
==
~~~
Exercise display:
- key1 : {{ key2 }}
- key2 : a

**Comment by qcoumes** [comment]
I don't think its possible to define keys using other key with the current language (except using builder).

I'm quite confused as why the example 1 is displaying  `a` for key 2, it should also display:
* key1 : a
* key2 : {{ key1 }}

since in the template, `{{ key2 }}` would be interpreted as `{{ key1 }}`, which should not be interpreted and stay as it stands (like in example 2).

**Comment by nimdanor** [comment]
The thing is the keys are "rendered" with the template mecanism  in a random order because a pl is an unordred dict, we will use the OrderedDic feature of python 3.7 and see what we get there.

The problem of the template position inside the pl is a good question, if  the place of the template is inportant then the dictionnary must be added at the extend line, this will have and impact on the parser. ....

Maybe 2 pass (files in a pl should stay small).

**Comment by ddoyen** [comment]
Two passes seems a good solution to me. It will allow all the "direct" substitutions without making the exercise authors overthink about the order (for now, i cannot see a use case with long substitution paths).

**Comment by nimdanor** [comment]
The radnering mecanisme shloud be used only for html rendering and not for calculation or exercice building. 
@ddoyen could you give me and exemple where the feature you are asking for (several level of templates) is realy usefull.

@qcoumes can we make a short list of jinja "rendered" variables. 
I have the following: text, texth,introduction, introductionh, form,  title, ??

**Comment by ddoyen** [comment]
I can think of at least two cases.

1. Keys with common part

For example, with JSXGraph exercises, we need to define two JSXGraph scripts: one script for the input step (where the graphical objects are moveable) and one script for the correction step (where the graphical objects are fixed and a solution is displayed). Of course, the scripts generally share a common part. We could avoid duplicate code with a third key.

~~~~
commonscript ==
...
==

inputscript ==
{{commonscript}}
...
==

correctionscript ==
{{commonscript}}
...
==
~~~~

2. Keys for feedback

I'd like to define the texts used in feedback outside the evaluator (as the text key is defined outside the before). It would allow to inherit an exercise and just change these texts.

Consider the following exercise `exo.pl`.
~~~~
before ==
...
sol = 1
==

textsolution = The solution is {{sol}}.

evaluator ==
...
feedback = {{textsolution}}
==
~~~~

It is then easy to change the feedback.

~~~~
extends = exo.pl

textsolution = La solution est {{sol}}.
~~~~

**Comment by qcoumes** [comment]
We have to check if replacing every variable could cause unintended effect.

The only problems I can see, is two variable calling each other or one calling itself:
```
var1 = {{ var2 }}
var2 = {{ var1 }}

var3 = {{ var3 }}
```
which are easy to catch.
