### ISSUE TITLE
[BUG] Servor Error when asking for stats or grade export

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/premierlangage#346]
## Description
With the activity "Nommage Variables Input Affectation Conditionnelles" in the cours view when i click on on of the twos buttons :
- stats 
- export 
i have this result :

Internal servor error ask  nicolas.c****@u-pem.fr

## Expected behavior
something else 

## How to reproduce
this morning (saturday) with nobody else on the machine it works ... 

## Config
On upem machines

**Comment by nimdanor** [comment]
Why did it worked friday afternoon ????

**Comment by nborie** [comment]
Ok, I think the behavior is currently this one :

This assume that the user has teacher status on the activities (on the full course...). If you click to get the stats (dashboard/XX) on a particular PLTP but you never did play with it (play/XX), you have an error (please mail to Cuvelier etc...).

Now, if you click on play on this PLTP, and even you do not do any exercise, if you re-ask for the dashboard/XX. Now it works...

So this bug is not so much disturbing It seems to me that the code assume that the viewer of the dashboard has grades for the dashboard he want to see.

Good luck in the bug investigation !

**Comment by plgitlogin** [comment]
I had this error while i already had a grade for this activity. 
I think the problem was in the get_or_create call (it's a method of a django Model) and it is fixed in a branch.

What i can't understand is that the error only occured last saturday and sunday. It worked before and the bug does'nt happen anymore.

**Comment by Pavell94000** [comment]
I had this error while i already had a grade for this activity.
I think the problem was in the get_or_create call (it's a method of a django Model) and it is fixed in a branch.

What i can't understand is that the error only occured last saturday and sunday. It worked before and the bug does'nt happen anymore.

**Comment by nimdanor** [comment]
Good news

Le jeu. 10 oct. 2019 à 13:26, Nicolas Borie <notifications@github.com> a
écrit :

**Comment by nborie** [comment]
Nicolas avec deux témoins (david et dominique pour ne pas les citer) ont constaté que les stats/notes déclanchent un seveur error 500 mais si on clique sur play (peu de temps avant), alors redemander les stats/notes fonctionnent...

**Comment by Pavell94000** [comment]
Should be fixed with the last version
